### ISSUE TITLE
Syntax error if run on Node v6

### ISSUE THREAD

**Issue by senpai-notices** [igorrmotta/fetch-fragment-matcher#1]
The trailing comma causes a syntax error in Node v6: 
https://github.com/igorrmotta/fetch-fragment-matcher/blob/c51d9b330c375c4a6eaa703067118a033ec11bfa/src/index.js#L44

### Fix
Remove the trailing comma:
```js
type => type.possibleTypes !== null
```

**Comment by igorrmotta** [comment]
@tanman-  can you submit a PR with the fix?

**Comment by senpai-notices** [comment]
@igorrmotta Done!
